/**
 * Attainment Model
 * Stores computed CO and PO attainment results for each course
 * Generated by the attainment calculation service
 */

const mongoose = require('mongoose');

/**
 * Schema for CO attainment record
 */
const coAttainmentSchema = new mongoose.Schema({
  coId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CourseOutcome',
    required: true
  },
  coNumber: {
    type: String,
    required: true
  },
  description: {
    type: String
  },
  // Success percentage from marks (0-100)
  successPercentage: {
    type: Number,
    min: 0,
    max: 100
  },
  // Direct attainment level (0-3)
  directAttainment: {
    type: Number,
    min: 0,
    max: 3
  },
  // Indirect attainment level (0-3) from feedback
  indirectAttainment: {
    type: Number,
    min: 0,
    max: 3
  },
  // Final attainment (weighted average)
  finalAttainment: {
    type: Number,
    min: 0,
    max: 3
  },
  // Number of students who attained this CO
  studentsAttained: {
    type: Number,
    default: 0
  },
  totalStudents: {
    type: Number,
    default: 0
  },
  // Average feedback rating for this CO
  averageFeedbackRating: {
    type: Number,
    min: 1,
    max: 5
  }
}, { _id: false });

/**
 * Schema for PO attainment record
 */
const poAttainmentSchema = new mongoose.Schema({
  poNumber: {
    type: String,
    required: true
  },
  poName: {
    type: String
  },
  // Weighted attainment value
  attainmentValue: {
    type: Number,
    min: 0,
    max: 3
  },
  // Contributing COs count
  contributingCOs: {
    type: Number,
    default: 0
  },
  // Sum of correlation values used
  totalCorrelationWeight: {
    type: Number,
    default: 0
  }
}, { _id: false });

const attainmentSchema = new mongoose.Schema({
  courseId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Course',
    required: [true, 'Course ID is required'],
    unique: true // One attainment record per course
  },
  coAttainments: [coAttainmentSchema],
  poAttainments: [poAttainmentSchema],
  generatedAt: {
    type: Date,
    default: Date.now
  },
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  // Warnings from calculation
  warnings: [{
    type: String
  }],
  // Summary statistics
  summary: {
    totalCOs: { type: Number, default: 0 },
    averageCOAttainment: { type: Number, default: 0 },
    averagePOAttainment: { type: Number, default: 0 },
    totalStudents: { type: Number, default: 0 },
    totalFeedbackResponses: { type: Number, default: 0 }
  }
}, {
  timestamps: true
});

// Index for faster queries
attainmentSchema.index({ generatedBy: 1 });

/**
 * Static to find attainment by course
 * @param {string} courseId - Course ID
 * @returns {Query} Mongoose query
 */
attainmentSchema.statics.findByCourse = function (courseId) {
  return this.findOne({ courseId });
};

/**
 * Method to get CO attainment by CO number
 * @param {string} coNumber - CO number (e.g., "CO1")
 * @returns {Object|null} CO attainment object
 */
attainmentSchema.methods.getCOAttainment = function (coNumber) {
  return this.coAttainments.find(co => co.coNumber === coNumber);
};

/**
 * Method to get PO attainment by PO number
 * @param {string} poNumber - PO number (e.g., "PO1")
 * @returns {Object|null} PO attainment object
 */
attainmentSchema.methods.getPOAttainment = function (poNumber) {
  return this.poAttainments.find(po => po.poNumber === poNumber);
};

/**
 * Static to get department-level PO attainment summary
 * @param {string} department - Department name
 * @param {string} academicYear - Academic year
 * @returns {Promise<Object>} Aggregated PO attainments and course list
 */
attainmentSchema.statics.getDepartmentSummary = async function (department, academicYear = null) {
  const Course = mongoose.model('Course');

  // Get all courses for the department
  const courseQuery = { department, isActive: true };
  if (academicYear) {
    courseQuery.academicYear = academicYear;
  }

  // FIX 1: Populate facultyId so faculty name is available downstream
  const courses = await Course.find(courseQuery)
    .select('_id courseCode courseName')
    .populate('facultyId', 'name email');

  const courseIds = courses.map(c => c._id);

  // FIX 2: Populate courseId with nested facultyId so faculty name reaches attainments
  const attainments = await this.find({ courseId: { $in: courseIds } })
    .populate({
      path: 'courseId',
      select: 'courseCode courseName semester facultyId',
      populate: {
        path: 'facultyId',
        select: 'name email'
      }
    });

  if (attainments.length === 0) {
    return { courses: [], attainments: [], poSummary: [] };
  }

  // Aggregate PO attainments across all courses
  const poAggregates = {};

  for (const att of attainments) {
    for (const po of att.poAttainments) {
      if (po.attainmentValue === null || po.attainmentValue === undefined) continue;

      if (!poAggregates[po.poNumber]) {
        poAggregates[po.poNumber] = {
          poNumber: po.poNumber,
          values: [],
          courses: []
        };
      }

      poAggregates[po.poNumber].values.push(po.attainmentValue);
      poAggregates[po.poNumber].courses.push({
        courseCode: att.courseId.courseCode,
        courseName: att.courseId.courseName,
        attainment: po.attainmentValue
      });
    }
  }

  // Calculate averages
  const poSummary = Object.values(poAggregates).map(agg => ({
    poNumber: agg.poNumber,
    averageAttainment: parseFloat(
      (agg.values.reduce((a, b) => a + b, 0) / agg.values.length).toFixed(2)
    ),
    courseCount: agg.courses.length,
    courses: agg.courses
  }));

  return {
    courses: courses.map(c => ({
      _id: c._id,
      courseCode: c.courseCode,
      courseName: c.courseName
    })),
    attainments: attainments.map(a => ({
      // FIX 3: Include _id so getDepartmentReport can do Attainment.findById(att._id)
      _id: a._id,
      courseId: a.courseId._id,
      courseCode: a.courseId.courseCode,
      courseName: a.courseId.courseName,
      semester: a.courseId.semester,
      // FIX 1: Include faculty name for the course-wise table in the frontend
      facultyName: a.courseId.facultyId?.name || null,
      averageCOAttainment: a.summary.averageCOAttainment,
      // FIX 2: Include averagePOAttainment for the course-wise table in the frontend
      averagePOAttainment: a.summary.averagePOAttainment,
      generatedAt: a.generatedAt
    })),
    poSummary
  };
};

const Attainment = mongoose.model('Attainment', attainmentSchema);

module.exports = Attainment;